# Generated by Django 5.2.7 on 2025-10-27 12:36

from django.db import migrations
from users.models import UserManager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', UserManager()),
            ],
        ),
    ]
